services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_DB: "lamoda"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
